version: '3.7'
  
services:
  foods-api:
    image: foods/foods-api
    build: ./foods-api
    ports:
      - "4000:4000"
    volumes:
      - ./foods-api:/home/node/api
  foods-app:
    image: foods/foods-app
    build: ./foods-app
    ports:
      - "3000:3000"
    volumes:
      - ./foods-app:/home/node/app
  db_foods:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DATADASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - foods_pg_data:/bhodedejava/postgresql

volumes:
  foods_pg_data:
