version: '3.7'
  
services:
  api_foods:
    image: foods/api_foods
    build: ./api-foods
    ports:
      - "4000:4000"
    volumes:
      - ./api-foods:/home/node/app
  db_foods:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DATADASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - foods_pg_data:/bitnami/postgresql

volumes:
  foods_pg_data:
